from sqlalchemy import Column, Integer, String, Text, DECIMAL, Boolean, TIMESTAMP, JSON
from sqlalchemy.sql import func

from ..database import Base


class Product(Base):
    """
    Modelo para productos Louder.
    Representa el catálogo de productos propios que se monitorean.
    Incluye historial de ventas mensual y datos de inventario.
    """
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    sku = Column(String(50), unique=True, nullable=False, index=True)
    ml_id = Column(String(50), unique=True, nullable=True, index=True)  # ID en Mercado Libre
    name = Column(String(255), nullable=False)
    title = Column(String(500))  # Raw title from CSV
    description = Column(Text)
    
    # Catalog fields from CSV
    brand = Column(String(100))  # Marca (WAHRGENOMEN, FUSSION, etc.)
    category = Column(String(200), index=True)  # Linea
    warehouse_location = Column(String(50))  # Ubicacion
    ml_url = Column(String(500))  # enlace
    
    # Pricing
    current_price = Column(DECIMAL(10, 2))
    cost_price = Column(DECIMAL(10, 2))  # costo from CSV
    cost = Column(DECIMAL(10, 2))  # Alias for compatibility
    min_margin_percent = Column(DECIMAL(5, 2), default=20.0)
    target_percentile = Column(Integer, default=50)  # Percentil objetivo (1-100)
    
    # Inventory
    current_stock = Column(Integer, default=0)  # Stock
    rotation_index = Column(DECIMAL(8, 2))  # rotacion
    total_sales = Column(Integer, default=0)  # totalSalidas
    
    # Monthly sales history (for elasticity analysis)
    sales_oct_2025 = Column(Integer, default=0)  # 2025-10
    sales_nov_2025 = Column(Integer, default=0)  # 2025-11
    sales_dec_2025 = Column(Integer, default=0)  # 2025-12
    sales_jan_2026 = Column(Integer, default=0)  # 2026-01
    
    # Enriched data (generated by CatalogEnrichmentAgent)
    normalized_title = Column(String(500))  # Clean title without SKU/brand
    generic_description = Column(Text)  # Human-readable description
    
    # Attributes y metadata (JSON para compatibilidad SQLite/PostgreSQL)
    attributes = Column(JSON)  # {size, power, impedance, color, etc.}
    key_specs = Column(JSON)  # Generated by enrichment agent
    search_keywords = Column(Text)  # Stored as comma-separated string for SQLite
    
    # Vector embedding - stored as TEXT in SQLite, will convert to list in Python
    embedding = Column(Text)  # JSON string of vector for SQLite compatibility
    
    # Status
    is_active = Column(Boolean, default=True)
    
    # Timestamps
    created_at = Column(TIMESTAMP, server_default=func.now())
    updated_at = Column(TIMESTAMP, server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<Product(id={self.id}, sku='{self.sku}', name='{self.name or self.title}', price={self.current_price})>"

    @property
    def min_price(self):
        """Calcula el precio mínimo basado en costo y margen mínimo"""
        cost = self.cost_price or self.cost
        if cost and self.min_margin_percent:
            return float(cost) * (1 + float(self.min_margin_percent) / 100)
        return None
    
    @property
    def monthly_sales_data(self):
        """Returns monthly sales as a list."""
        return [
            self.sales_oct_2025 or 0,
            self.sales_nov_2025 or 0,
            self.sales_dec_2025 or 0,
            self.sales_jan_2026 or 0
        ]

    @property
    def current_margin_percent(self):
        """Calcula el margen actual en porcentaje"""
        if self.cost and self.current_price and float(self.cost) > 0:
            return ((float(self.current_price) - float(self.cost)) / float(self.cost)) * 100
        return None
